version: '3'
services:
  app:
    build:
      context: .
      dockerfile: .cloud/docker/php/Dockerfile
    env_file:
      - .env
    ports:
      - 8080:80
    volumes:
    - .:/var/www/html

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
